- include: "setup.yml"
  tags:
    - "setup"

- name: "AUR | Default AUR packages"
  set_fact:
    default_aur_packages:
      - "visual-studio-code-bin"
      - "docker"
      - "slack-desktop"
      - "neovim"
      - "git-delta"
      - "ripgrep"
      - "fzf"
      - "fd"
      - "autorandr"
      - "obsidian"
      - "rofi"
      - "bitwarden"
      - "nvm"

- name: "AUR | Install AUR packages"
  kewlfft.aur.aur:
    use: "yay"
    state: "latest"
    name: "{{ item }}"
  with_items: "{{ default_aur_packages + additional_aur_packages }}"

  become_user: "aur_builder"
  become: true

- include: "docker.yml"
