- include: "setup.yml"
  tags:
    - "setup"

- name: "AUR | Install AUR packages"
  kewlfft.aur.aur:
    use: "yay"
    state: "latest"
    name: "{{ item }}"
  with_items:
      - "visual-studio-code-bin"
      - "docker"
      - "slack-desktop"
      - "neovim"
      - "git-delta"
      - "ripgrep"
      - "fzf"
      - "fd"
  become_user: "aur_builder"
  become: true

- include: "docker.yml"
